#ifndef WGVK_SPIRV_H
#define WGVK_SPIRV_H

#include <stdint.h>
#include <stddef.h>

#define WGVK_SPV_MAGIC 0x07230203
#define WGVK_SPV_VERSION_1_0 0x00010000

typedef enum {
    WGVK_SPV_OP_NOP = 0,
    WGVK_SPV_OP_UNDEF = 1,
    WGVK_SPV_OP_SOURCE = 3,
    WGVK_SPV_OP_NAME = 5,
    WGVK_SPV_OP_MEMBER_NAME = 6,
    WGVK_SPV_OP_EXTENSION = 10,
    WGVK_SPV_OP_EXT_INST_IMPORT = 11,
    WGVK_SPV_OP_MEMORY_MODEL = 14,
    WGVK_SPV_OP_ENTRY_POINT = 15,
    WGVK_SPV_OP_EXECUTION_MODE = 16,
    WGVK_SPV_OP_CAPABILITY = 17,
    WGVK_SPV_OP_TYPE_VOID = 19,
    WGVK_SPV_OP_TYPE_BOOL = 20,
    WGVK_SPV_OP_TYPE_INT = 21,
    WGVK_SPV_OP_TYPE_FLOAT = 22,
    WGVK_SPV_OP_TYPE_VECTOR = 23,
    WGVK_SPV_OP_TYPE_MATRIX = 24,
    WGVK_SPV_OP_TYPE_IMAGE = 25,
    WGVK_SPV_OP_TYPE_SAMPLER = 26,
    WGVK_SPV_OP_TYPE_SAMPLED_IMAGE = 27,
    WGVK_SPV_OP_TYPE_ARRAY = 28,
    WGVK_SPV_OP_TYPE_RUNTIME_ARRAY = 29,
    WGVK_SPV_OP_TYPE_STRUCT = 30,
    WGVK_SPV_OP_TYPE_POINTER = 32,
    WGVK_SPV_OP_TYPE_FUNCTION = 33,
    WGVK_SPV_OP_CONSTANT_TRUE = 41,
    WGVK_SPV_OP_CONSTANT_FALSE = 42,
    WGVK_SPV_OP_CONSTANT = 43,
    WGVK_SPV_OP_CONSTANT_COMPOSITE = 44,
    WGVK_SPV_OP_CONSTANT_NULL = 46,
    WGVK_SPV_OP_SPEC_CONSTANT_TRUE = 48,
    WGVK_SPV_OP_SPEC_CONSTANT_FALSE = 49,
    WGVK_SPV_OP_SPEC_CONSTANT = 50,
    WGVK_SPV_OP_SPEC_CONSTANT_COMPOSITE = 51,
    WGVK_SPV_OP_SPEC_CONSTANT_OP = 52,
    WGVK_SPV_OP_FUNCTION = 54,
    WGVK_SPV_OP_FUNCTION_PARAMETER = 55,
    WGVK_SPV_OP_FUNCTION_END = 56,
    WGVK_SPV_OP_FUNCTION_CALL = 57,
    WGVK_SPV_OP_VARIABLE = 59,
    WGVK_SPV_OP_IMAGE_TEXEL_POINTER = 60,
    WGVK_SPV_OP_LOAD = 61,
    WGVK_SPV_OP_STORE = 62,
    WGVK_SPV_OP_COPY_MEMORY = 63,
    WGVK_SPV_OP_COPY_MEMORY_SIZED = 64,
    WGVK_SPV_OP_ACCESS_CHAIN = 65,
    WGVK_SPV_OP_IN_BOUNDS_ACCESS_CHAIN = 66,
    WGVK_SPV_OP_PTR_ACCESS_CHAIN = 67,
    WGVK_SPV_OP_ARRAY_LENGTH = 68,
    WGVK_SPV_OP_GENERIC_PTR_MEM_SEMANTICS = 69,
    WGVK_SPV_OP_IN_BOUNDS_PTR_ACCESS_CHAIN = 70,
    WGVK_SPV_OP_DECORATE = 71,
    WGVK_SPV_OP_MEMBER_DECORATE = 72,
    WGVK_SPV_OP_DECORATION_GROUP = 73,
    WGVK_SPV_OP_GROUP_DECORATE = 74,
    WGVK_SPV_OP_GROUP_MEMBER_DECORATE = 75,
    WGVK_SPV_OP_VECTOR_SHUFFLE = 76,
    WGVK_SPV_OP_COMPOSITE_EXTRACT = 81,
    WGVK_SPV_OP_COMPOSITE_INSERT = 82,
    WGVK_SPV_OP_COPY_OBJECT = 83,
    WGVK_SPV_OP_COPY_LOGICAL = 84,
    WGVK_SPV_OP_TRANSPOSE = 85,
    WGVK_SPV_OP_SAMPLED_IMAGE = 86,
    WGVK_SPV_OP_IMAGE_SAMPLE_IMPLICIT_LOD = 87,
    WGVK_SPV_OP_IMAGE_SAMPLE_EXPLICIT_LOD = 88,
    WGVK_SPV_OP_IMAGE_SAMPLE_DREF_IMPLICIT_LOD = 89,
    WGVK_SPV_OP_IMAGE_SAMPLE_DREF_EXPLICIT_LOD = 90,
    WGVK_SPV_OP_IMAGE = 91,
    WGVK_SPV_OP_CONVERT_F_TO_U = 109,
    WGVK_SPV_OP_CONVERT_F_TO_S = 110,
    WGVK_SPV_OP_CONVERT_S_TO_F = 111,
    WGVK_SPV_OP_CONVERT_U_TO_F = 112,
    WGVK_SPV_OP_U_CONVERT = 113,
    WGVK_SPV_OP_S_CONVERT = 114,
    WGVK_SPV_OP_F_CONVERT = 115,
    WGVK_SPV_OP_QUANTIZE_TO_F16 = 116,
    WGVK_SPV_OP_BITCAST = 124,
    WGVK_SPV_OP_SNEGATE = 126,
    WGVK_SPV_OP_FNEGATE = 127,
    WGVK_SPV_OP_IADD = 128,
    WGVK_SPV_OP_FADD = 129,
    WGVK_SPV_OP_ISUB = 130,
    WGVK_SPV_OP_FSUB = 131,
    WGVK_SPV_OP_IMUL = 132,
    WGVK_SPV_OP_FMUL = 133,
    WGVK_SPV_OP_UDIV = 134,
    WGVK_SPV_OP_SDIV = 135,
    WGVK_SPV_OP_FDIV = 136,
    WGVK_SPV_OP_UMOD = 137,
    WGVK_SPV_OP_SREM = 138,
    WGVK_SPV_OP_FMOD = 139,
    WGVK_SPV_OP_VECTOR_TIMES_SCALAR = 140,
    WGVK_SPV_OP_MATRIX_TIMES_SCALAR = 141,
    WGVK_SPV_OP_VECTOR_TIMES_MATRIX = 142,
    WGVK_SPV_OP_MATRIX_TIMES_VECTOR = 143,
    WGVK_SPV_OP_MATRIX_TIMES_MATRIX = 144,
    WGVK_SPV_OP_OUTER_PRODUCT = 145,
    WGVK_SPV_OP_DOT = 148,
    WGVK_SPV_OP_SHIFT_RIGHT_LOGICAL = 149,
    WGVK_SPV_OP_SHIFT_RIGHT_ARITHMETIC = 150,
    WGVK_SPV_OP_SHIFT_LEFT_LOGICAL = 151,
    WGVK_SPV_OP_BITWISE_OR = 152,
    WGVK_SPV_OP_BITWISE_XOR = 153,
    WGVK_SPV_OP_BITWISE_AND = 154,
    WGVK_SPV_OP_NOT = 155,
    WGVK_SPV_OP_LOGICAL_EQUAL = 164,
    WGVK_SPV_OP_LOGICAL_NOT_EQUAL = 165,
    WGVK_SPV_OP_LOGICAL_OR = 166,
    WGVK_SPV_OP_LOGICAL_AND = 167,
    WGVK_SPV_OP_LOGICAL_NOT = 168,
    WGVK_SPV_OP_SELECT = 169,
    WGVK_SPV_OP_I_EQUAL = 170,
    WGVK_SPV_OP_I_NOT_EQUAL = 171,
    WGVK_SPV_OP_U_GREATER_THAN = 172,
    WGVK_SPV_OP_S_GREATER_THAN = 173,
    WGVK_SPV_OP_U_GREATER_THAN_EQUAL = 174,
    WGVK_SPV_OP_S_GREATER_THAN_EQUAL = 175,
    WGVK_SPV_OP_U_LESS_THAN = 176,
    WGVK_SPV_OP_S_LESS_THAN = 177,
    WGVK_SPV_OP_U_LESS_THAN_EQUAL = 178,
    WGVK_SPV_OP_S_LESS_THAN_EQUAL = 179,
    WGVK_SPV_OP_F_ORD_EQUAL = 180,
    WGVK_SPV_OP_F_UNORD_EQUAL = 181,
    WGVK_SPV_OP_F_ORD_NOT_EQUAL = 182,
    WGVK_SPV_OP_F_UNORD_NOT_EQUAL = 183,
    WGVK_SPV_OP_F_ORD_LESS_THAN = 184,
    WGVK_SPV_OP_F_UNORD_LESS_THAN = 185,
    WGVK_SPV_OP_F_ORD_GREATER_THAN = 186,
    WGVK_SPV_OP_F_UNORD_GREATER_THAN = 187,
    WGVK_SPV_OP_F_ORD_LESS_THAN_EQUAL = 188,
    WGVK_SPV_OP_F_UNORD_LESS_THAN_EQUAL = 189,
    WGVK_SPV_OP_F_ORD_GREATER_THAN_EQUAL = 190,
    WGVK_SPV_OP_F_UNORD_GREATER_THAN_EQUAL = 191,
    WGVK_SPV_OP_PHI = 245,
    WGVK_SPV_OP_LOOP_MERGE = 246,
    WGVK_SPV_OP_SELECTION_MERGE = 247,
    WGVK_SPV_OP_LABEL = 248,
    WGVK_SPV_OP_BRANCH = 249,
    WGVK_SPV_OP_BRANCH_CONDITIONAL = 250,
    WGVK_SPV_OP_SWITCH = 251,
    WGVK_SPV_OP_KILL = 252,
    WGVK_SPV_OP_RETURN = 253,
    WGVK_SPV_OP_RETURN_VALUE = 254,
    WGVK_SPV_OP_UNREACHABLE = 255,
    WGVK_SPV_OP_ISNAN = 234,
    WGVK_SPV_OP_ISINF = 235,
} WgvkSpvOp;

typedef enum {
    WGVK_GLSL_ROUND = 1,
    WGVK_GLSL_ROUND_EVEN = 2,
    WGVK_GLSL_TRUNC = 3,
    WGVK_GLSL_FABS = 4,
    WGVK_GLSL_FLOOR = 5,
    WGVK_GLSL_CEIL = 6,
    WGVK_GLSL_FRACT = 7,
    WGVK_GLSL_SQRT = 10,
    WGVK_GLSL_INVERSE_SQRT = 11,
    WGVK_GLSL_ABS = 12,
    WGVK_GLSL_SIGN = 13,
    WGVK_GLSL_FMIN = 14,
    WGVK_GLSL_FMAX = 15,
    WGVK_GLSL_FCLAMP = 16,
    WGVK_GLSL_MIN = 17,
    WGVK_GLSL_MAX = 18,
    WGVK_GLSL_CLAMP = 19,
    WGVK_GLSL_MIX = 20,
    WGVK_GLSL_STEP = 21,
    WGVK_GLSL_SMOOTHSTEP = 22,
    WGVK_GLSL_SIN = 23,
    WGVK_GLSL_COS = 24,
    WGVK_GLSL_TAN = 25,
    WGVK_GLSL_ASIN = 26,
    WGVK_GLSL_ACOS = 27,
    WGVK_GLSL_ATAN = 28,
    WGVK_GLSL_SINH = 29,
    WGVK_GLSL_COSH = 30,
    WGVK_GLSL_TANH = 31,
    WGVK_GLSL_ATAN2 = 32,
    WGVK_GLSL_POW = 33,
    WGVK_GLSL_EXP = 34,
    WGVK_GLSL_LOG = 35,
    WGVK_GLSL_EXP2 = 36,
    WGVK_GLSL_LOG2 = 37,
    WGVK_GLSL_LENGTH = 66,
    WGVK_GLSL_DISTANCE = 67,
    WGVK_GLSL_CROSS = 68,
    WGVK_GLSL_NORMALIZE = 69,
    WGVK_GLSL_FACE_FORWARD = 70,
    WGVK_GLSL_REFLECT = 71,
    WGVK_GLSL_REFRACT = 72,
} WgvkGlslExtOp;

typedef enum {
    WGVK_SPV_STORAGE_CLASS_UNIFORM_CONSTANT = 0,
    WGVK_SPV_STORAGE_CLASS_INPUT = 1,
    WGVK_SPV_STORAGE_CLASS_UNIFORM = 2,
    WGVK_SPV_STORAGE_CLASS_OUTPUT = 3,
    WGVK_SPV_STORAGE_CLASS_WORKGROUP = 4,
    WGVK_SPV_STORAGE_CLASS_CROSS_WORKGROUP = 5,
    WGVK_SPV_STORAGE_CLASS_PRIVATE = 6,
    WGVK_SPV_STORAGE_CLASS_FUNCTION = 7,
    WGVK_SPV_STORAGE_CLASS_GENERIC = 8,
    WGVK_SPV_STORAGE_CLASS_PUSH_CONSTANT = 9,
    WGVK_SPV_STORAGE_CLASS_ATOMIC_COUNTER = 10,
    WGVK_SPV_STORAGE_CLASS_IMAGE = 11,
    WGVK_SPV_STORAGE_CLASS_STORAGE_BUFFER = 12,
} WgvkSpvStorageClass;

typedef enum {
    WGVK_SPV_DECORATION_BLOCK = 2,
    WGVK_SPV_DECORATION_BUFFER_BLOCK = 3,
    WGVK_SPV_DECORATION_BUILTIN = 11,
    WGVK_SPV_DECORATION_LOCATION = 30,
    WGVK_SPV_DECORATION_COMPONENT = 31,
    WGVK_SPV_DECORATION_INDEX = 32,
    WGVK_SPV_DECORATION_BINDING = 33,
    WGVK_SPV_DECORATION_DESCRIPTOR_SET = 34,
    WGVK_SPV_DECORATION_OFFSET = 35,
    WGVK_SPV_DECORATION_ARRAY_STRIDE = 44,
    WGVK_SPV_DECORATION_MATRIX_STRIDE = 46,
    WGVK_SPV_DECORATION_NON_WRITABLE = 34,
    WGVK_SPV_DECORATION_COL_MAJOR = 41,
    WGVK_SPV_DECORATION_ROW_MAJOR = 42,
} WgvkSpvDecoration;

typedef enum {
    WGVK_SPV_BUILTIN_POSITION = 0,
    WGVK_SPV_BUILTIN_POINT_SIZE = 1,
    WGVK_SPV_BUILTIN_CLIP_DISTANCE = 3,
    WGVK_SPV_BUILTIN_CULL_DISTANCE = 4,
    WGVK_SPV_BUILTIN_VERTEX_ID = 5,
    WGVK_SPV_BUILTIN_INSTANCE_ID = 6,
    WGVK_SPV_BUILTIN_PRIMITIVE_ID = 7,
    WGVK_SPV_BUILTIN_INVOCATION_ID = 8,
    WGVK_SPV_BUILTIN_LAYER = 9,
    WGVK_SPV_BUILTIN_VIEWPORT_INDEX = 10,
    WGVK_SPV_BUILTIN_FRAG_COORD = 15,
    WGVK_SPV_BUILTIN_FRONT_FACING = 16,
    WGVK_SPV_BUILTIN_POINT_COORD = 17,
    WGVK_SPV_BUILTIN_SAMPLE_ID = 18,
    WGVK_SPV_BUILTIN_SAMPLE_POS = 19,
    WGVK_SPV_BUILTIN_SAMPLE_MASK = 20,
    WGVK_SPV_BUILTIN_FRAG_DEPTH = 22,
    WGVK_SPV_BUILTIN_NUM_WORKGROUPS = 24,
    WGVK_SPV_BUILTIN_WORKGROUP_SIZE = 25,
    WGVK_SPV_BUILTIN_WORKGROUP_ID = 26,
    WGVK_SPV_BUILTIN_LOCAL_INVOCATION_ID = 27,
    WGVK_SPV_BUILTIN_GLOBAL_INVOCATION_ID = 28,
    WGVK_SPV_BUILTIN_LOCAL_INVOCATION_INDEX = 29,
    WGVK_SPV_BUILTIN_VERTEX_INDEX = 44,
    WGVK_SPV_BUILTIN_INSTANCE_INDEX = 45,
} WgvkSpvBuiltin;

typedef enum {
    WGVK_SPV_EXEC_MODEL_VERTEX = 0,
    WGVK_SPV_EXEC_MODEL_TESSELLATION_CONTROL = 1,
    WGVK_SPV_EXEC_MODEL_TESSELLATION_EVALUATION = 2,
    WGVK_SPV_EXEC_MODEL_GEOMETRY = 3,
    WGVK_SPV_EXEC_MODEL_FRAGMENT = 4,
    WGVK_SPV_EXEC_MODEL_GL_COMPUTE = 5,
    WGVK_SPV_EXEC_MODEL_KERNEL = 6,
} WgvkSpvExecutionModel;

#define WGVK_MAX_TYPES 1024
#define WGVK_MAX_CONSTANTS 1024
#define WGVK_MAX_VARIABLES 256
#define WGVK_MAX_DECORATIONS 512
#define WGVK_MAX_ENTRY_POINTS 8
#define WGVK_MAX_INSTRUCTIONS 8192
#define WGVK_MAX_BLOCKS 256

typedef struct {
    uint32_t id;
    uint32_t op;
    uint32_t scalar_type;
    uint32_t width;
    uint32_t signedness;
    uint32_t vector_size;
    uint32_t matrix_cols;
    uint32_t matrix_rows;
    uint32_t element_type;
    uint32_t member_count;
    uint32_t member_types[16];
    uint32_t length;
    uint32_t storage_class;
    uint32_t return_type;
    uint32_t param_count;
    uint32_t param_types[8];
} WgvkSpvType;

typedef struct {
    uint32_t id;
    uint32_t type_id;
    uint32_t value[4];
    float fvalue[4];
    uint32_t component_count;
    uint32_t component_ids[16];
} WgvkSpvConstant;

typedef struct {
    uint32_t id;
    uint32_t type_id;
    uint32_t storage_class;
    const char* name;
} WgvkSpvVariable;

typedef struct {
    uint32_t target_id;
    uint32_t decoration;
    uint32_t value;
    uint32_t member;
} WgvkSpvDecorationInfo;

typedef struct {
    uint32_t exec_model;
    uint32_t entry_point_id;
    const char* name;
    uint32_t interface_count;
    uint32_t interface_ids[32];
} WgvkSpvEntryPoint;

typedef struct {
    uint32_t opcode;
    uint32_t result_id;
    uint32_t result_type_id;
    uint32_t operands[16];
    uint32_t operand_count;
} WgvkSpvInstruction;

typedef struct {
    uint32_t label_id;
    WgvkSpvInstruction instructions[64];
    uint32_t instruction_count;
} WgvkSpvBlock;

typedef struct {
    uint32_t id;
    uint32_t result_type_id;
    const char* name;
    WgvkSpvBlock blocks[WGVK_MAX_BLOCKS];
    uint32_t block_count;
    uint32_t current_block;
} WgvkSpvFunction;

typedef struct {
    const uint32_t* words;
    size_t word_count;
    size_t cursor;
    
    WgvkSpvType types[WGVK_MAX_TYPES];
    uint32_t type_count;
    
    WgvkSpvConstant constants[WGVK_MAX_CONSTANTS];
    uint32_t constant_count;
    
    WgvkSpvVariable variables[WGVK_MAX_VARIABLES];
    uint32_t variable_count;
    
    WgvkSpvDecorationInfo decorations[WGVK_MAX_DECORATIONS];
    uint32_t decoration_count;
    
    WgvkSpvEntryPoint entry_points[WGVK_MAX_ENTRY_POINTS];
    uint32_t entry_point_count;

    WgvkSpvFunction functions[64];
    uint32_t function_count;
    WgvkSpvFunction* current_function;
    
    char string_buffer[16384];
    size_t string_cursor;
} WgvkSpvModule;

int wgvk_spirv_parse(WgvkSpvModule* module, const uint32_t* code, size_t size);
void wgvk_spirv_free(WgvkSpvModule* module);
WgvkSpvType* wgvk_spirv_get_type(WgvkSpvModule* module, uint32_t id);
WgvkSpvConstant* wgvk_spirv_get_constant(WgvkSpvModule* module, uint32_t id);
WgvkSpvVariable* wgvk_spirv_get_variable(WgvkSpvModule* module, uint32_t id);
WgvkSpvDecorationInfo* wgvk_spirv_get_decoration(WgvkSpvModule* module, uint32_t id, uint32_t decoration);
const char* wgvk_spirv_get_entry_name(WgvkSpvModule* module, uint32_t exec_model);
WgvkSpvFunction* wgvk_spirv_get_function(WgvkSpvModule* module, uint32_t id);

#endif
